### PR TITLE
Update controller gen

### PR DESCRIPTION
**Pull request by Hyperkid123**
The current version does not work on the latest ARM MacOS. There are some issues with go version and OS: https://github.com/kubernetes-sigs/controller-tools/issues/888

```
make generate
/Users/martin/insights/frontend-operator/testbin/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x0 pc=0x104f47a54]
goroutine 74 [running]:
go/types.(*Checker).handleBailout(0x140001dac00, 0x14000e69d18)
```

using the v15 fixest the problems

### TODO:
- [x] fix which files needs tobe regenerated
- [x] fix the tests

### CODE REVIEW

**Comment by Hyperkid123** [comment]
@psav I assume I have to re-generate some things. I see the controller gen version is referenced in a bunch of yaml 
files

**Comment by maknop** [comment]
I'm also getting this issue! I'm glad I'm not alone here.

**Comment by Hyperkid123** [comment]
@maknop I think I got it working locally. (still need to fix konflux). Can you verify that this PR fixes your issue as well?

**Comment by Hyperkid123** [comment]
@psav @adamrdrew Ok I think I got it ready for review. I assume the Jenkins failure is still tied to the environment itself and not the changes I made. But I'd still like to wait until it works.

**Comment by maknop** [comment]
@Hyperkid123 That works for me. Thank you :smile:

**Review by psav — APPROVED** [review]

**Comment by psav** [comment]
Approved - we should ensure that all our operators are updated to new "standards" regularly.

**Pull request merged**
