### PR TITLE
Update navigation specs

### PR DESCRIPTION
**Pull request by Hyperkid123**
Jira: https://issues.redhat.com/browse/RHCLOUD-33913

### Changes
- Update frontend and bundle resources with new navigation spec
- Stop generating bundle data
  - The data is not used in environments so it should not be missing from anywhere
  - The reconciliation will be updated as a follow-up to match the new requirements

@psav @adamrdrew can you please confirm that not generating the navigation data will not totally break ephemeral envs? AFAIk it should be using the static files.

### CODE REVIEW

**Comment by adamrdrew** [comment]
> @psav @adamrdrew can you please confirm that not generating the navigation data will not totally break ephemeral envs? AFAIk it should be using the static files.

I deployed a frontend to ephemeral and Chrome had the full set of navigation items (menus, etc) so that tells me it should be using what chrome-service is feeding it.

**Comment by Hyperkid123** [comment]
OK, thanks @adamrdrew that is what I though was happening. Just want to be extra careful.

**Review by adamrdrew — APPROVED** [review]
LGTM

**Pull request merged**
